### ISSUE TITLE
有没有办法给导出的文件对应的事件名

### ISSUE THREAD

**Issue by gaiyayishi** [Virace/lol-audio-events-hashtable#1]
比如给对应皮肤下的wem，自动按照表格命名为“Play_sfx_AatroxSkin21_AatroxRAttack1_OnCast”

**Comment by Virace** [comment]
可以看看这个库，https://github.com/Virace/lol_extract_voice ，main.py中https://github.com/Virace/lol_extract_voice/blob/6dc7afad2de504903b885383699bb1f7ab1ac9d0/main.py#L199 如果只需要事件的哈希表 那么201 202注释掉就好了。哈希表会生成在输出目录/hashes 里面

**Comment by gaiyayishi** [comment]
> 可以看看这个库，https://github.com/Virace/lol_extract_voice ，main.py中https://github.com/Virace/lol_extract_voice/blob/6dc7afad2de504903b885383699bb1f7ab1ac9d0/main.py#L199 如果只需要事件的哈希表 那么201 202注释掉就好了。哈希表会生成在输出目录/hashes 里面

我的意思是把事件名称直接写成提取出来的音频文件名字，现在是一堆数字乱码

**Comment by Virace** [comment]
提取的事件里面就有音频ID，如果想要改成事件名就额外写个循环改名呗。
